import { z } from "zod";
import type { SupabaseClient } from "@supabase/supabase-js";
import { DiscoveryRuntimeSchema, SessionSchema } from "../../core/mc04.ts";
import type { RuntimePersistencePort } from "../../ports/runtime-persistence.ts";
import type { AgentBDatabase } from "./database.types.ts";
import { FoundationError } from "../../core/identity-access.ts";
const runtimeRow = z.strictObject({ discovery_id:z.string(), runtime_version:z.number(), freshness:z.string(), current_state:z.unknown(), pending:z.unknown() });
export class SupabaseRuntimePersistence implements RuntimePersistencePort {
 private client: any; constructor(client: SupabaseClient<AgentBDatabase>){this.client=client;}
 async read(i:any){const {data,error}=await this.client.from("agent_b_runtime_state").select("discovery_id,runtime_version,freshness,current_state,pending").eq("discovery_id",i.discoveryId).maybeSingle();if(error)throw new FoundationError(error.code==="42501"?"ACCESS_DENIED":"PROVIDER_UNAVAILABLE");if(!data)return null;const r=runtimeRow.parse(data);return DiscoveryRuntimeSchema.parse({discoveryId:r.discovery_id,runtimeVersion:r.runtime_version,freshness:r.freshness,current:r.current_state,pending:r.pending});}
 async mutate(i:any){if(!i.runtime||i.runtime.runtimeVersion!==i.expectedRuntimeVersion+1)throw new FoundationError("INVALID_INPUT");const {data,error}=await this.client.from("agent_b_runtime_state").update({runtime_version:i.runtime.runtimeVersion,freshness:i.runtime.freshness,current_state:i.runtime.current,pending:i.runtime.pending}).eq("discovery_id",i.discoveryId).eq("runtime_version",i.expectedRuntimeVersion).select().single();if(error)throw new FoundationError(error.code==="PGRST116"||error.code==="40001"?"CONCURRENT_MODIFICATION":"PROVIDER_UNAVAILABLE");const r=runtimeRow.parse(data);return DiscoveryRuntimeSchema.parse({discoveryId:r.discovery_id,runtimeVersion:r.runtime_version,freshness:r.freshness,current:r.current_state,pending:r.pending});}
 async createSession(i:any){const {data,error}=await this.client.from("agent_b_sessions").insert({session_id:i.sessionId,discovery_id:i.discoveryId,previous_session_id:i.previousSessionId,lifecycle:"OPEN",created_at:i.now}).select().single();if(error)throw new FoundationError(error.code==="23505"?"CONCURRENT_MODIFICATION":"PROVIDER_UNAVAILABLE");return SessionSchema.parse({sessionId:data.session_id,discoveryId:data.discovery_id,previousSessionId:data.previous_session_id,lifecycle:data.lifecycle,createdAt:data.created_at});}
 async transition(i:any){const {data,error}=await this.client.from("agent_b_sessions").update({lifecycle:i.lifecycle}).eq("session_id",i.sessionId).eq("discovery_id",i.discoveryId).eq("lifecycle","OPEN").select().single();if(error)throw new FoundationError(error.code==="PGRST116"?"CONCURRENT_MODIFICATION":"PROVIDER_UNAVAILABLE");return SessionSchema.parse({sessionId:data.session_id,discoveryId:data.discovery_id,previousSessionId:data.previous_session_id,lifecycle:data.lifecycle,createdAt:data.created_at});}
 async transitionSession(i:any){ return this.transition(i); }
 async listSessions(i:any){const {data,error}=await this.client.from("agent_b_sessions").select("session_id,discovery_id,previous_session_id,lifecycle,created_at").eq("discovery_id",i.discoveryId).order("created_at");if(error)throw new FoundationError("PROVIDER_UNAVAILABLE");return (data??[]).map((d:any)=>SessionSchema.parse({sessionId:d.session_id,discoveryId:d.discovery_id,previousSessionId:d.previous_session_id,lifecycle:d.lifecycle,createdAt:d.created_at}));}
}
