import assert from "node:assert/strict"; import test from "node:test";
import { RuntimeFoundation } from "../../lib/agent-b/application/runtime-foundation.ts";
import { DiscoveryRuntimeSchema } from "../../lib/agent-b/core/mc04.ts"; import { FoundationError } from "../../lib/agent-b/core/identity-access.ts";
const runtime=DiscoveryRuntimeSchema.parse({discoveryId:"d",runtimeVersion:0,freshness:"CURRENT",current:{pendingIds:[]},pending:[]}); const identity={current:async()=>({identityId:"u",kind:"ANONYMOUS"})} as any;
function p(){let r=runtime;const sessions:any[]=[];return {read:async()=>r,mutate:async(i:any)=>{if(i.expectedRuntimeVersion!==r.runtimeVersion)throw new FoundationError("CONCURRENT_MODIFICATION");r=i.runtime;return r;},createSession:async(i:any)=>{const s={sessionId:i.sessionId,discoveryId:i.discoveryId,previousSessionId:i.previousSessionId,lifecycle:"OPEN",createdAt:i.now};sessions.push(s);return s;},transitionSession:async(i:any)=>{const s=sessions.find(x=>x.sessionId===i.sessionId);if(!s||s.lifecycle!=="OPEN")throw new FoundationError("CONCURRENT_MODIFICATION");s.lifecycle=i.lifecycle;return s;},listSessions:async()=>sessions,resumeAtomic:async(i:any)=>{if(i.expectedRuntimeVersion!==r.runtimeVersion)throw new FoundationError("CONCURRENT_MODIFICATION");if(i.previousSessionId)sessions.find(x=>x.sessionId===i.previousSessionId).lifecycle="INTERRUPTED";r=i.runtime;const s={sessionId:i.sessionId,discoveryId:i.discoveryId,previousSessionId:i.previousSessionId,lifecycle:"OPEN",createdAt:i.now};sessions.push(s);return {runtime:r,session:s};}};}
test("B04 runtimeVersion requires monotonic expected CAS",async()=>{const q=p();const s=new RuntimeFoundation(identity,q as any);await s.mutate({discoveryId:"d",expectedRuntimeVersion:0,runtime:{...runtime,runtimeVersion:1}});await assert.rejects(()=>s.mutate({discoveryId:"d",expectedRuntimeVersion:0,runtime:{...runtime,runtimeVersion:1}}));});
test("B04 session resume creates a new linked Session and does not reopen",async()=>{const q=p();const s=new RuntimeFoundation(identity,q as any);const a=await s.openSession({discoveryId:"d",sessionId:"s1",previousSessionId:null,now:"2026-09-22T12:00:00Z"});const b=await s.resume({discoveryId:"d",operationId:"00000000-0000-4000-8000-000000000001",sessionId:"s2",expectedRuntimeVersion:0,now:"2026-09-22T12:00:00Z"});assert.equal(a.lifecycle,"INTERRUPTED");assert.equal(b.context.previousSessionId,"s1");assert.equal(b.session.previousSessionId,"s1");assert.equal((await q.listSessions())[0].lifecycle,"INTERRUPTED");});
test("B04 authentication is required before runtime access",async()=>{const s=new RuntimeFoundation({current:async()=>null} as any,p() as any);await assert.rejects(()=>s.read({discoveryId:"d"}),(e:any)=>e.code==="AUTHENTICATION_REQUIRED");});
test("B04 pending and freshness remain referential runtime state",()=>{const x=DiscoveryRuntimeSchema.parse({...runtime,freshness:"REEVALUATION_REQUIRED",pending:[{pendingId:"p",state:"PENDING",reference:"classification"}],current:{pendingIds:["p"]}});assert.equal(x.pending[0].state,"PENDING");});
