import { z } from "zod";
import { DiscoveryIdSchema, RuntimeVersionSchema, SessionIdSchema, TimestampSchema } from "../core/primitives.ts";
import { DiscoveryRuntimeSchema, ResumeContextSchema, SessionSchema, type ResumeContext } from "../core/mc04.ts";
import { FoundationError } from "../core/identity-access.ts";
import type { IdentityPort } from "../ports/identity.ts";
import type { RuntimePersistencePort } from "../ports/runtime-persistence.ts";
const id = z.strictObject({ discoveryId: DiscoveryIdSchema });
export class RuntimeFoundation {
  private identity: IdentityPort; private persistence: RuntimePersistencePort;
  constructor(identity: IdentityPort, persistence: RuntimePersistencePort) { this.identity = identity; this.persistence = persistence; }
  private async principal() { const p = await this.identity.current(); if (!p) throw new FoundationError("AUTHENTICATION_REQUIRED"); return p; }
  async read(input: unknown) { const p = id.safeParse(input); if (!p.success) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); return this.persistence.read({ identityId: i.identityId, ...p.data }); }
  async mutate(input: unknown) { const p = z.strictObject({ discoveryId: DiscoveryIdSchema, expectedRuntimeVersion: RuntimeVersionSchema, runtime: DiscoveryRuntimeSchema }).safeParse(input); if (!p.success || p.data.runtime.discoveryId !== p.data.discoveryId || p.data.runtime.runtimeVersion !== p.data.expectedRuntimeVersion + 1) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); return this.persistence.mutate({ identityId: i.identityId, ...p.data }); }
  async openSession(input: unknown) { const p = z.strictObject({ discoveryId: DiscoveryIdSchema, sessionId: SessionIdSchema, previousSessionId: SessionIdSchema.nullable(), now: TimestampSchema }).safeParse(input); if (!p.success) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); return this.persistence.createSession({ identityId: i.identityId, ...p.data }); }
  async transition(input: unknown) { const p = z.strictObject({ discoveryId: DiscoveryIdSchema, sessionId: SessionIdSchema, lifecycle: z.enum(["INTERRUPTED", "CLOSED"]) }).safeParse(input); if (!p.success) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); return this.persistence.transitionSession({ identityId: i.identityId, ...p.data }); }
  async resume(input: unknown): Promise<{ context: ResumeContext; session: import("../core/mc04.ts").Session }> { const p = z.strictObject({ discoveryId: DiscoveryIdSchema, operationId: z.string().uuid(), sessionId: SessionIdSchema, expectedRuntimeVersion: RuntimeVersionSchema, now: TimestampSchema }).safeParse(input); if (!p.success) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); const runtime = await this.persistence.read({ identityId: i.identityId, discoveryId: p.data.discoveryId }); if (!runtime || runtime.runtimeVersion !== p.data.expectedRuntimeVersion) throw new FoundationError("CONCURRENT_MODIFICATION"); const sessions = await this.persistence.listSessions({ identityId: i.identityId, discoveryId: p.data.discoveryId }); const previous = sessions.find((s) => s.lifecycle === "OPEN") ?? sessions.at(-1) ?? null; const context = ResumeContextSchema.parse({ discoveryId: runtime.discoveryId, runtimeVersion: runtime.runtimeVersion, current: runtime.current, pending: runtime.pending, previousSessionId: previous?.sessionId ?? null }); const result = await this.persistence.resumeAtomic({ identityId: i.identityId, discoveryId: p.data.discoveryId, operationId: p.data.operationId, sessionId: p.data.sessionId, expectedRuntimeVersion: p.data.expectedRuntimeVersion, previousSessionId: previous?.sessionId ?? null, runtime: { ...runtime, runtimeVersion: RuntimeVersionSchema.parse(runtime.runtimeVersion + 1) }, now: p.data.now }); return { context, session: SessionSchema.parse(result.session) }; }
}
