import { z } from "zod";
import { DiscoveryIdSchema, RuntimeVersionSchema, SessionIdSchema, TimestampSchema } from "../core/primitives.ts";
import { DiscoveryRuntimeSchema, ResumeContextSchema, SessionSchema, type ResumeContext } from "../core/mc04.ts";
import { FoundationError } from "../core/identity-access.ts";
import type { IdentityPort } from "../ports/identity.ts";
import type { RuntimePersistencePort } from "../ports/runtime-persistence.ts";
const id = z.strictObject({ discoveryId: DiscoveryIdSchema });
export class RuntimeFoundation {
  private identity: IdentityPort; private persistence: RuntimePersistencePort;
  constructor(identity: IdentityPort, persistence: RuntimePersistencePort) { this.identity = identity; this.persistence = persistence; }
  private async principal() { const p = await this.identity.current(); if (!p) throw new FoundationError("AUTHENTICATION_REQUIRED"); return p; }
  async read(input: unknown) { const p = id.safeParse(input); if (!p.success) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); return this.persistence.read({ identityId: i.identityId, ...p.data }); }
  async mutate(input: unknown) { const p = z.strictObject({ discoveryId: DiscoveryIdSchema, expectedRuntimeVersion: RuntimeVersionSchema, runtime: DiscoveryRuntimeSchema }).safeParse(input); if (!p.success || p.data.runtime.discoveryId !== p.data.discoveryId || p.data.runtime.runtimeVersion !== p.data.expectedRuntimeVersion + 1) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); return this.persistence.mutate({ identityId: i.identityId, ...p.data }); }
  async openSession(input: unknown) { const p = z.strictObject({ discoveryId: DiscoveryIdSchema, sessionId: SessionIdSchema, previousSessionId: SessionIdSchema.nullable(), now: TimestampSchema }).safeParse(input); if (!p.success) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); return this.persistence.createSession({ identityId: i.identityId, ...p.data }); }
  async transition(input: unknown) { const p = z.strictObject({ discoveryId: DiscoveryIdSchema, sessionId: SessionIdSchema, lifecycle: z.enum(["INTERRUPTED", "CLOSED"]) }).safeParse(input); if (!p.success) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); return this.persistence.transitionSession({ identityId: i.identityId, ...p.data }); }
  async resume(input: unknown): Promise<{ context: ResumeContext; session: import("../core/mc04.ts").Session }> { const p = id.safeParse(input); if (!p.success) throw new FoundationError("INVALID_INPUT"); const i = await this.principal(); const runtime = await this.persistence.read({ identityId: i.identityId, ...p.data }); if (!runtime) throw new FoundationError("ACCESS_DENIED"); const sessions = await this.persistence.listSessions({ identityId: i.identityId, ...p.data }); const previous = sessions.find((s) => s.lifecycle === "OPEN") ?? sessions.at(-1) ?? null; if (previous?.lifecycle === "OPEN") await this.persistence.transitionSession({ identityId: i.identityId, discoveryId: p.data.discoveryId, sessionId: previous.sessionId, lifecycle: "INTERRUPTED" }); const context = ResumeContextSchema.parse({ discoveryId: runtime.discoveryId, runtimeVersion: runtime.runtimeVersion, current: runtime.current, pending: runtime.pending, previousSessionId: previous?.sessionId ?? null }); const session = await this.persistence.createSession({ identityId: i.identityId, discoveryId: p.data.discoveryId, previousSessionId: context.previousSessionId, sessionId: `session-${Date.now()}` as never, now: new Date().toISOString() as never }); return { context, session: SessionSchema.parse(session) }; }
}
